# Generated by Django 5.0.3 on 2024-03-20 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_order_cart_order_cart_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='cart_product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api.cartproduct'),
        ),
    ]
